replicaCount: 1

image:
  repository: ghcr.io/gumamon/go-metrics-sample
  tag: "latest"
  pullPolicy: IfNotPresent

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: /metrics

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    # - name: metrics
    #   port: 8000
    #   targetPort: 8000

resources: {}
