apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-metrics-sample
  labels:
    app: go-metrics-sample
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-metrics-sample
  template:
    metadata:
      labels:
        app: go-metrics-sample
    spec:
      containers:
        - name: go-metrics-sample
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
