apiVersion: v1
kind: Service
metadata:
  name: go-metrics-sample
  labels:
    app: go-metrics-sample
spec:
  selector:
    app: go-metrics-sample
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
